# PLACEHOLDER — replace with the hardware-configuration.nix generated by the NixOS installer.
#
# This is a stub for a future laptop that does not exist yet. The desktop host
# imports the real file from /etc/nixos/hardware-configuration.nix on first boot;
# do the same here, then lock it in:
#
#   cp /etc/nixos/hardware-configuration.nix hosts/laptop/hardware-configuration.nix
#   # Then update configuration.nix to import ./hardware-configuration.nix instead.
#
# The kernel modules / filesystems below are generic placeholders — the installer's
# generated config will differ (Intel laptops in particular need different drivers).

{ modulesPath, lib, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod"
  ];

  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Adjust these to match your actual disk UUIDs (use `lsblk -f` to find them).
  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = lib.mkDefault {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = lib.mkDefault [ { device = "/dev/disk/by-label/swap"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
