# PLACEHOLDER — replace with the hardware-configuration.nix generated by the NixOS installer.
#
# The NixOS graphical installer writes the real file to /etc/nixos/hardware-configuration.nix.
# configuration.nix currently imports from that absolute path, so this file is not used
# on real hardware until you lock it in:
#
#   cp /etc/nixos/hardware-configuration.nix hosts/desktop/hardware-configuration.nix
#   # Then update configuration.nix to import ./hardware-configuration.nix instead.
#
# For VM testing with `nix build .#vm`, this file is largely ignored — the build-vm
# target uses a tmpfs root and injects its own virtual disk config automatically.

{ modulesPath, lib, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod"
    # virtio drivers for QEMU VM testing
    "virtio_pci" "virtio_scsi" "virtio_blk" "virtio_net"
  ];

  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Adjust these to match your actual disk UUIDs (use `lsblk -f` to find them).
  # For the VM, build-vm ignores these and uses its own image.
  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = lib.mkDefault {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = lib.mkDefault [ { device = "/dev/disk/by-label/swap"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
