{ inputs, pkgs, ... }: {
  nixpkgs.config.allowUnfree = true;

  imports = [
    # The live machine's real hardware config, generated by nixos-generate-config and
    # committed here. Pure relative import — no --impure needed.
    ./hardware-configuration.nix
    ../../modules/system.nix
    ../../modules/desktop.nix
    ../../modules/packages.nix
    ../../modules/peripherals.nix
  ];

  networking.hostName = "zenith-pc-ryzen-7";

  users.users.ni = {
    isNormalUser = true;
    description = "ni";
    extraGroups = [ "wheel" "networkmanager" "video" "audio" "input" "render" ];
    shell = pkgs.fish;
    # Default password — intentional, change with `passwd ni` after first boot
    password = "nixos";
  };

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    # Back up (don't clobber) any pre-existing dotfile home-manager wants to own,
    # e.g. a hand-set ~/.config/solaar/rules.yaml before it became managed.
    backupFileExtension = "hm-bak";
    extraSpecialArgs = { inherit inputs; };
    users.ni = import ../../home/default.nix;
  };

  # Initial value — do not change after first deploy (controls stateful defaults)
  system.stateVersion = "25.05";
}
